name: tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/tests.yml"
      - "Makefile"
      - "geopkg/**/*.py"
      - "tests/**/*.py"

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install Poetry
        run: make get-poetry

      - name: Add system path to Poetry
        run: echo $HOME/.poetry/bin >> $GITHUB_PATH

      - name: Install dependencies
        run: make build-env

      - name: Run Pytest
        run: make tests
